ALTER TABLE "users"
  ADD COLUMN "resetOtpFailedAttempts" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "resetOtpBlockedUntil" TIMESTAMP(3),
  ADD COLUMN "resetOtpLastSentAt" TIMESTAMP(3),
  ADD COLUMN "resetOtpHourlySendCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "resetOtpHourlyWindowStart" TIMESTAMP(3),
  ADD COLUMN "resetOtpDailySendCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "resetOtpDailyWindowStart" TIMESTAMP(3);

ALTER TABLE "email_verifications"
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "failedAttempts" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "blockedUntil" TIMESTAMP(3),
  ADD COLUMN "lastSentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "hourlySendCount" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "hourlyWindowStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "dailySendCount" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "dailyWindowStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

DELETE FROM "email_verifications";

UPDATE "users"
SET "resetOtpCode" = NULL,
    "resetOtpExpiresAt" = NULL;
